// DO NOT EDIT THIS FILE. This file is autogenerated by Upserv Foundations.
import { Controller } from '@hotwired/stimulus'

export default class extends Controller {
  connect() {
    this.radios = this.element.querySelectorAll('input[type="radio"]')
    for (var i = 0; i < this.radios.length; i++) {
      var radio = this.radios[i]
      radio.addEventListener('change', () => {
        this.checkAllRadioStates()
      })
    }
  }

  checkAllRadioStates() {
    for (var i = 0; i < this.radios.length; i++) {
      var radio = this.radios[i]
      this.checkRadioState(radio)
    }
  }

  checkRadioState(radio) {
    const hideElements = document.getElementsByClassName(
      radio.dataset.hideClass
    )
    for (let i = 0; i < hideElements.length; i++) {
      var hideElement = hideElements[i]
      hideElement.style.display = radio.checked
        ? 'none'
        : hideElement.dataset.display
    }

    const showElements = document.getElementsByClassName(
      radio.dataset.showClass
    )
    for (let i = 0; i < showElements.length; i++) {
      let showElement = showElements[i]
      showElement.style.display = radio.checked
        ? showElement.dataset.display
        : 'none'
    }
  }
}
