// DO NOT EDIT THIS FILE. This file is autogenerated by Upserv Foundations.
import { Controller } from '@hotwired/stimulus'

// Connects to data-controller="radio-display-toggle"
export default class extends Controller {
  connect() {
    this.displayToggleClass = this.element.dataset.displayToggleClass
    this.toggleElements = document.getElementsByClassName(
      this.displayToggleClass
    )
    this.options = this.element.querySelectorAll('OPTION')
    this.toggleDisplay()
  }

  toggleDisplay() {
    // hide all toggle elements
    for (let i = 0; i < this.toggleElements.length; i++) {
      let toggleElement = this.toggleElements[i]
      toggleElement.style.display = 'none'
    }
    let showClass
    // display selected toggle elements
    for (let i = 0; i < this.options.length; i++) {
      let option = this.options[i]
      if (option.selected == true) {
        showClass = option.dataset.showClass
      }
    }
    const showElements = document.getElementsByClassName(showClass)
    for (let i = 0; i < showElements.length; i++) {
      let showElement = showElements[i]
      showElement.style.display = showElement.dataset.display
    }
  }
}
