// DO NOT EDIT THIS FILE. This file is autogenerated by Upserv Foundations.
import { Controller } from '@hotwired/stimulus'

export default class extends Controller {
  connect() {
    this.element.style.height = '1px'
    // honestly I can't remember why I chose 32. I think it's because
    // it makes the input a little larger so you now it's a text area
    // and so it's not super jerky when you add the first line but idk
    let height = 32 + this.element.scrollHeight
    // set minimum of 46 which is height of regular input field (42)
    if (height < 46) height = 46
    // let height = 42
    this.element.style.height = height + 'px'
    this.element.style.overflow = 'hidden'
    this.element.addEventListener('keyup', function () {
      this.style.height = '1px'
      this.style.height = 20 + this.scrollHeight + 'px'
    })
  }
}
