// DO NOT EDIT THIS FILE. This file is autogenerated by Upserv Foundations.
function hideDropDowns() {
  const dropdownPopUpClones = document.getElementsByClassName(
    'dropdown-items-clone'
  )

  for (const dropdownPopUpClone of dropdownPopUpClones) {
    dropdownPopUpClone.remove()
  }
}

// Only hide drop downs on click when the mouse is not over an
// element where if clicked, we would want to keep the dropdown
// (ex. an accordion inside the dropdown)
document.addEventListener('click', () => {
  const hoverDoNotClose = document.querySelector(
    '.keep-dropdown-on-click:hover'
  )
  if (!hoverDoNotClose) {
    hideDropDowns()
  }
})

// Hide the dropdown on the wheel action unless
// the wheel action is on the dropdown itself
document.addEventListener('wheel', () => {
  const hoveredDropdown = document.querySelector('.dropdown-items:hover')
  if (!hoveredDropdown) {
    hideDropDowns()
  }
})

// Always hide on resize
window.addEventListener('resize', () => {
  hideDropDowns(true)
})
