// DO NOT EDIT THIS FILE. This file is autogenerated by Upserv Foundations.
function hideDropDowns(ignoreMousePosition = false) {
  if (!ignoreMousePosition) {
    const hoveredDropdown = document.querySelector('.dropdown-items:hover')
    if (hoveredDropdown) {
      return // Don't hide if mouse is over a dropdown
    }
  }

  const dropdownPopUpClones = document.getElementsByClassName(
    'dropdown-items-clone'
  )

  for (const dropdownPopUpClone of dropdownPopUpClones) {
    dropdownPopUpClone.remove()
  }
}

document.addEventListener('click', () => {
  hideDropDowns()
})

document.addEventListener('wheel', () => {
  hideDropDowns()
})

window.addEventListener('resize', () => {
  hideDropDowns(true) // Always hide on resize
})
