// DO NOT EDIT THIS FILE. This file is autogenerated by Upserv Foundations.
import { Controller } from '@hotwired/stimulus'

export default class extends Controller {
  connect() {
    // set the style based on the width of the cardHeader at load
    this.setStyleBasedOnWidth()
    // add event listner window resize event to set style based on width
    window.addEventListener('resize', this.setStyleBasedOnWidth.bind(this))
  }

  setStyleBasedOnWidth() {
    // Select the cardHeader element
    const cardHeader = this.element
    // get the minPx data attribute and convert to integer
    const minPx = parseInt(cardHeader.dataset.minPx) || 400

    // Get the computed width of the cardHeader element
    const cardHeaderWidth = cardHeader.getBoundingClientRect().width

    // add or remove the small class based on the width
    if (cardHeaderWidth < minPx) {
      cardHeader.classList.add('small')
    } else {
      cardHeader.classList.remove('small')
    }
  }
}
