// DO NOT EDIT THIS FILE. This file is autogenerated by Upserv Foundations.
import { Controller } from '@hotwired/stimulus'

export default class extends Controller {
  connect() {
    // set the style based on the width of the cardHeader at load
    this.setStyleBasedOnWidth()

    // Create a new ResizeObserver instance (we want to trigger
    // the setStyleBasedOnWidth function when the width of the
    // element changes, not necessarily when the window changes size)
    const resizeObserver = new ResizeObserver(() => {
      this.setStyleBasedOnWidth()
    })
    resizeObserver.observe(this.element)
  }

  setStyleBasedOnWidth() {
    // Select the cardHeader element
    const cardHeader = this.element
    // get the minPx data attribute and convert to integer
    // 335 here pairs well with 350 on inline card wrapper
    const minPx = parseInt(cardHeader.dataset.minPx) || 335

    // Get the computed width of the cardHeader element
    const cardHeaderWidth = cardHeader.getBoundingClientRect().width

    // add or remove the small class based on the width
    if (cardHeaderWidth < minPx) {
      cardHeader.classList.add('small')
    } else {
      cardHeader.classList.remove('small')
    }
  }
}
