// DO NOT EDIT THIS FILE. This file is autogenerated by Upserv Foundations.
import { Controller } from '@hotwired/stimulus'

export default class extends Controller {
  connect() {
    // set visibility to visible (starts as hidden to prevent resize / flicker on load)
    // card header could flicker if the card is small (it will start regular and then
    // snap to small mode)
    // inline cards could flicker (they start as width 100% then snap to the correct width)
    this.element.style.visibility = 'visible'
  }
}
