// DO NOT EDIT THIS FILE. This file is autogenerated by Upserv Foundations.
import { Controller } from '@hotwired/stimulus'

export default class extends Controller {
  connect() {
    // set visibility to visible (starts as hidden to prevent resize / flicker on load)
    // page header could flicker if the page is small (it will start regular and then
    // snap to small mode)
    this.element.style.visibility = 'visible'
    // set the style based on the width of the pageHeader at load
    this.setStyleBasedOnWidth()
    // add event listner window resize event to set style based on width
    window.addEventListener('resize', this.setStyleBasedOnWidth.bind(this))
  }

  setStyleBasedOnWidth() {
    // Select the pageHeader element
    const pageHeader = this.element
    // get the minPx data attribute and convert to integer
    const minPx = parseInt(pageHeader.dataset.minPx) || 400

    // Get the computed width of the pageHeader element
    const pageHeaderWidth = pageHeader.getBoundingClientRect().width

    // add or remove the small class based on the width
    if (pageHeaderWidth < minPx) {
      pageHeader.classList.add('small')
    } else {
      pageHeader.classList.remove('small')
    }
  }
}
