// DO NOT EDIT THIS FILE. This file is autogenerated by Upserv Foundations.
// tooltip_controller.js
import { Controller } from '@hotwired/stimulus'

export default class extends Controller {
  static targets = ['button', 'message']

  showMessage() {
    // NOTE: need to set to block before updateTooltipPosition because we need to know
    // height and width
    this.messageTarget.style.display = 'block'
    this.updateTooltipPosition()
    // NOTE: immetiately set back to none because we will render the clone and not the
    // actual message target (see note below regarding cloning)
    this.messageTarget.style.display = 'none'
  }

  hideMessage() {
    // since we are cloning, rather than hiding (ie setting display to none),
    // we instead simply remove the clone
    this.messageTargetClone.remove()
  }

  updateTooltipPosition() {
    const buttonRect = this.buttonTarget.getBoundingClientRect()

    const makeUpForVerticalPadding = 4
    const widthSpacer = 8

    const screenWidth = window.innerWidth

    const spaceLeft = buttonRect.left
    const spaceRight = screenWidth - buttonRect.right

    const screenHeight = window.innerHeight
    const spaceTop = buttonRect.top
    const spaceBottom = screenHeight - buttonRect.bottom

    const messageWidthInt = parseFloat(
      window.getComputedStyle(this.messageTarget).getPropertyValue('width')
    )
    const messageHeightInt = parseFloat(
      window.getComputedStyle(this.messageTarget).getPropertyValue('height')
    )
    const buttonHeightInt = parseFloat(
      window.getComputedStyle(this.buttonTarget).getPropertyValue('height')
    )
    // NOTE: if the messageTarget is the descendant of a fixed or absolute container
    // then the fixed position will be relative the that container and not the
    // screen... so we clone it render the clone at the bottom of the page body
    // so that we can ensure the fixed position is relative to the screen
    this.messageTargetClone = this.copyElementWithDescendants(
      this.messageTarget
    )
    // bottom right
    if (
      spaceBottom >=
        messageHeightInt - buttonHeightInt - makeUpForVerticalPadding &&
      spaceRight >= widthSpacer + messageWidthInt
    ) {
      this.positionBottomRight(
        buttonRect,
        widthSpacer,
        makeUpForVerticalPadding
      )

      // bottom left
    } else if (
      spaceBottom >=
        messageHeightInt - buttonHeightInt - makeUpForVerticalPadding &&
      spaceLeft >= widthSpacer + messageWidthInt
    ) {
      this.messageTargetClone.style.left =
        buttonRect.left - widthSpacer - messageWidthInt + 'px'
      this.messageTargetClone.style.top =
        buttonRect.top - makeUpForVerticalPadding + 'px'

      // top right
    } else if (
      spaceTop >=
        messageHeightInt - buttonHeightInt - makeUpForVerticalPadding &&
      spaceRight >= widthSpacer + messageWidthInt
    ) {
      this.messageTargetClone.style.left =
        buttonRect.right + widthSpacer + 'px'
      this.messageTargetClone.style.top =
        buttonRect.bottom - messageHeightInt + makeUpForVerticalPadding + 'px'

      // top left
    } else if (
      spaceTop >=
        messageHeightInt - buttonHeightInt - makeUpForVerticalPadding &&
      spaceLeft >= widthSpacer + messageWidthInt
    ) {
      this.messageTargetClone.style.left =
        buttonRect.left - widthSpacer - messageWidthInt + 'px'
      this.messageTargetClone.style.top =
        buttonRect.bottom - messageHeightInt + makeUpForVerticalPadding + 'px'

      // bottom right fall back if no space
      // NOTE: should fall back to region with most space rather than defaulting to bottom right... Add this later
    } else {
      this.positionBottomRight(
        buttonRect,
        widthSpacer,
        makeUpForVerticalPadding
      )
    }
    document.body.appendChild(this.messageTargetClone)
  }

  positionBottomRight(buttonRect, widthSpacer, makeUpForVerticalPadding) {
    this.messageTargetClone.style.left = buttonRect.right + widthSpacer + 'px'
    this.messageTargetClone.style.top =
      buttonRect.top - makeUpForVerticalPadding + 'px'
  }

  // Recursively copy parent and all child elements and their descendants
  // and only return the parent (becuase children will be attached to parent)
  copyElementWithDescendants(element, parent = null) {
    const clone = element.cloneNode(true)
    if (parent) parent.appendChild(clone)
    for (const child of element.children) {
      this.copyElementWithDescendants(child, clone)
    }
    if (parent === null) return clone
  }
}
